Feature: Verifying the facebook details

//any details - login details/payment details/any thing actually
//Inside the features as we can write 'n' number of scenarios
//what purpose that you going to use particular scenario
//Generate the snippet--- its tells about Methods
//snippets are generated by run the Test Runner Class
//adactinhotelapp.com

Scenario Outline: Verifying the login details with valid credencials 
Given User hitting the "<url>" landing  on the facebook loging page
When User enter the valid "<userName>" and "<passWord>"
Then User click on the Login button and enter into the home page 
And  User verifying the Url in the Home Page

Examples:
|url|userName|passWord|
|https://en-gb.facebook.com/|giridharan28it@gmail.com|Suve_Rosebud8|

